/*
 * Java domain class for entity "EserviceMotorDetails" 
 * Created on 2022-10-17 ( Date ISO 2022-10-17 - Time 11:50:07 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.common.req;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import lombok.*;


import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceMotorDetailsSaveReq implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("CustomerReferenceNo")
    private String   customerReferenceNo ;
    
    @JsonProperty("RequestReferenceNo")
    private String   requestReferenceNo ;
	
	@JsonProperty("Idnumber")
    private String     idNumber     ;
	@JsonProperty("VehicleId")
    private String   vehicleId    ;
	@JsonProperty("accident")
	private String     accident     ;
	@JsonProperty("Gpstrackinginstalled")
    private String     gpsTrackingInstalled ;
	
	@JsonProperty("Insurancetype")
    private String     insuranceType ;

	@JsonProperty("Chassisnumber")
    private String     chassisNumber ;
	@JsonProperty("Vehiclemake")
    private String     vehicleMake  ;

	@JsonProperty("Vehcilemodel")
    private String     vehcileModel ;

	@JsonProperty("VehicleType")
    private String     vehicleType  ;


	@JsonProperty("periodOfInsurance")
    private String     periodOfInsurance ;
	
	@JsonProperty("WindScreenSumInsured")
    private String     windScreenSumInsured ;
	@JsonProperty("AcccessoriesSumInsured")
    private String     acccessoriesSumInsured ;
//	@JsonProperty("AccessoriesInformation")
//    private String     accessoriesInformation ;
//	@JsonProperty("Windscreencoverrequired")
//    private String     windScreenCoverRequired ;
	@JsonProperty("SumInsured")
    private String     sumInsured   ;

	@JsonProperty("TppdIncreaeLimit")
    private String     tppdIncreaeLimit ;
//	@JsonProperty("InsurerSettlement")
//    private String     insurerSettlement ;
//	@JsonProperty("PolicyType")
//    private String     policyType   ;


//	@JsonProperty("AdditionalCircumstances")
//    private String     additionalCircumstances ;
	@JsonProperty("BranchCode")
    private String     branchCode ;
	@JsonProperty("BrokerBranchCode")
    private String     brokerBranchCode ;
	@JsonProperty("AgencyCode")
    private String     agencyCode ;


	@JsonProperty("ProductId")
    private String  productId ;

	@JsonProperty("InsuranceId")
    private String  companyId ;

	@JsonProperty("InsuranceClass")
    private String  insuranceClass ;
//
//	@JsonProperty("OwnerCategory")
//    private String ownerCategory;

	@JsonProperty("NcdYn")
    private String    ncdYn ;

	@JsonProperty("HavePromoCode")
    private String     havepromocode ;
	
	@JsonProperty("PromoCode")
    private String     promocode    ;


	@JsonFormat(pattern="dd/MM/yyyy")
	@JsonProperty("PolicyStartDate")
    private Date policyStartDate;

	@JsonFormat(pattern="dd/MM/yyyy")
	@JsonProperty("PolicyEndDate")
    private Date policyEndDate;

	
	@JsonProperty("Status")
    private String   status;

	@JsonProperty("CreatedBy")
    private String  createdBy;
	
	@JsonProperty("Currency")
    private String  currency;
	
	@JsonProperty("ExchangeRate")
    private String  exchangeRate;
	
	@JsonProperty("CollateralYn")
    private String  collateralYn;
	
	@JsonProperty("BorrowerType")
    private String  borrowerType;
	
	@JsonProperty("CollateralName")
    private String collateralName;
	
	@JsonProperty("FirstLossPayee")
    private String firstLossPayee;
	
	@JsonProperty("FleetOwnerYn")
    private String fleetOwnerYn;
	
	@JsonProperty("NoOfVehicles")
    private String noOfVehicles;	
	@JsonProperty("NoOfComprehensives")
    private String noOfComprehensives;	
	@JsonProperty("ClaimRatio")
    private String claimRatio;	
	
	@JsonProperty("SavedFrom")
    private String   savedFrom;
	
	@JsonProperty("BrokerCode")
	private String brokerCode;
	
	@JsonProperty("LoginId")
	private String loginId;
	
	@JsonProperty("AcExecutiveId")
	private String acExecutiveId;
	
	@JsonProperty("UserType")
	private String userType;
	
	@JsonProperty("SubUserType")
	private String subUserType;
	
	@JsonProperty("ApplicationId")
	private String applicationId;
	
	@JsonProperty("BdmCode")
	private String bdmCode;
	
	@JsonProperty("SourceType")
	private String sourceType;
	
	@JsonProperty("CustomerCode")
	private String customerCode;
	
//	@JsonProperty("BankCode")
//    private String    bankCode;

	  
    @JsonProperty("EndorsementDate") //EndorsementDate
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date       endorsementDate ;
    @JsonProperty("EndorsementRemarks") // EndorsementRemarks
    private String     endorsementRemarks ;    
    @JsonProperty("EndorsementEffectiveDate") // EndorsementEffectiveDate
    @JsonFormat(pattern = "dd/MM/yyyy")
    private Date       endorsementEffdate ;
    @JsonProperty("OrginalPolicyNo") // OrginalPolicyNo
    private String     originalPolicyNo ;
    @JsonProperty("EndtPrevPolicyNo") // EndtPrevPolicyNo
    private String     endtPrevPolicyNo ;
    @JsonProperty("EndtPrevQuoteNo") // EndtPrevQuoteNo
    private String     endtPrevQuoteNo ;
    @JsonProperty("EndtCount")  // EndtCount
    private BigDecimal endtCount ;
    @JsonProperty("EndtStatus") //EndtStatus
    private String     endtStatus ;   
    @JsonProperty("IsFinanceEndt") //IsFinanceEndt
    private String     isFinaceYn ;  
    @JsonProperty("EndtCategoryDesc") //EndtCategoryDesc
    private String     endtCategDesc ;
    @JsonProperty("EndorsementType") //EndorsementType
    private Integer    endorsementType ;

    @JsonProperty("EndorsementTypeDesc") // EndorsementTypeDesc
    private String     endorsementTypeDesc ;
    
    @JsonProperty("PolicyNo")
    private String policyNo;
    
    @JsonProperty("EndorsementYn")
    private String endorsementYn;
    
	@JsonProperty("Motorusage")
	private String     motorUsage   ;

    // Refined 23-05-2023
//	@JsonProperty("MotorCategory")
//  private String     motorCategory ;
//	@JsonProperty("Motorusage")
//  private String     motorUsage   ;
//	@JsonProperty("Registrationnumber")
//  private String     registrationNumber ;
//	@JsonProperty("ModelNumber")
//  private String     modelNumber  ;
//	@JsonProperty("EngineNumber")
//  private String     engineNumber ;
//	@JsonProperty("FuelType")
//  private String     fuelType     ;

//	@JsonFormat(pattern="dd/MM/yyyy")
//	@JsonProperty("RegistrationYear")
//  private Date   registrationYear ;
//	@JsonProperty("SeatingCapacity")
//  private Integer    seatingCapacity ;
//	@JsonProperty("CubicCapacity")
//  private Double     cubicCapacity ;
//	@JsonProperty("Color")
//  private String     color        ;
//
//	@JsonProperty("Grossweight")
//  private Double     grossWeight  ;
//	@JsonProperty("Tareweight")
//  private Double     tareWeight   ;
//	@JsonProperty("Actualpremium")
//  private Double     actualPremium ;
//	@JsonProperty("CoverNoteNo")
//  private String     covernoteNo  ;
//	@JsonProperty("Stickerno")
//  private String     stickerNo    ;
//	@JsonProperty("NumberOfAxels")
//  private Integer    numberOfAxels ;
//	@JsonProperty("AxelDistance")
//  private Double     axelDistance ;
//	@JsonProperty("OverRidePercentage")
//  private String    overridePercentage   ;
//	@JsonProperty("TppdFreeLimit")
//  private String     tppdFreeLimit ;
//	    
    
//	@JsonProperty("RadioOrCasseteplayer")
//  private Double     radioorcasseteplayer ;
//	@JsonProperty("RoofRack")
//  private Double     roofRack     ;
//	@JsonProperty("SpotFogLamp")   
//	private Double     spotFogLamp  ;
//	@JsonProperty("TrailerDetails")
//  private String     trailerDetails ;
//
//	@JsonProperty("DrivenByDesc")
//  private String     drivenByDesc     ;
//
//	@JsonProperty("HoldInsurancePolicy")
//  private String     holdInsurancePolicy ;
//	@JsonProperty("NoOfClaims")
//  private Integer    noOfClaims   ;   
    
//	@JsonProperty("SectionId")
//  private String    sectionId ;    
    //
//	@JsonProperty("NcdYears")   
//    private Integer ncdYears;   
    

//	@JsonProperty("CityLimit")
//	  private String     cityLimit;

//	@JsonProperty("ManufactureYear")
//    private String manufactureYear;        
	
//	@JsonProperty("DriverDetails")
//	private List<DriverDetailsSaveReq> driverDetails;
//	@JsonProperty("CommissionType")
//	private String commissionType;	
//	@JsonProperty("DriverYn")
//	private String driverYn;   
    
    
    // Old Commented  20-04-2023

//	@JsonFormat(pattern="dd/MM/yyyy")
//	@JsonProperty("UpdatedDate")
//    private Date updatedDate;
//
//	@JsonProperty("UpdatedBy")
//    private String  updatedBy;
//	@JsonProperty("ManufactureAge")
//  private Integer manufactureAge;
//	@JsonProperty("RegistrationAge")
//  private Integer registrationAge;
//	@JsonProperty("VehicleInterestedCompany")
//  private String     vehicleInterestedCompany ;
//	@JsonProperty("InterestedCompanyDetails")
//  private String     interestedCompanyDetails ;
//	@JsonProperty("OtherVehicle")
//  private String     otherVehicle ;
//	@JsonProperty("OtherVehicleDetails")
//  private String     otherVehicleDetails ;
//	@JsonProperty("OtherInsurance")
//  private String     otherInsurance ;
//	@JsonProperty("OtherInsuranceDetails")
//  private String     otherInsuranceDetails ;
//	@JsonProperty("PolicyTypeDesc")
//  private String     policyTypeDesc   ;	
//	@JsonProperty("Drivenby")
//  private String     drivenBy     ;
//	@JsonProperty("VehiclemakeDesc")
//  private String     vehicleMakeDesc  ;
//	@JsonProperty("VehcilemodelDesc")
//  private String     vehcileModelDesc ;
//	@JsonProperty("VehicleTypeDesc")
//  private String     vehicleTypeDesc  ;
//	@JsonProperty("FuelTypeDesc")
//  private String     fuelTypeDesc     ;
//	@JsonProperty("ColorDesc")
//  private String     colorDesc ;
    
}
