/*
 * Java domain class for entity "CityMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.Date;

import com.maan.eway.bean.CityMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.CityMasterId;
/**
 * <h2>CityMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:28
 * <p>
 * Description: "CityMaster" Repository
 */
 
 
 
public interface CityMasterRepository  extends JpaRepository<CityMaster,CityMasterId > , JpaSpecificationExecutor<CityMaster> {

	Long countByCityNameOrderByEntryDateDesc(String cityName);

	Long countByCityIdAndStateIdAndCountryIdAndStatusAndEffectiveDateStartLessThanEqual(Integer valueOf,
			Integer valueOf2, String valueOf3, String string, Date today);



}
