/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.ContentAndRisk;
import com.maan.eway.bean.ContentAndRiskId;
/**
 * <h2>BankMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:26
 * <p>
 * Description: "BankMaster" Repository
 */
 
 
 
public interface ContentAndRiskRepository  extends JpaRepository<ContentAndRisk,ContentAndRiskId > , JpaSpecificationExecutor<ContentAndRisk> {

	

	ContentAndRisk findByQuoteNoAndRiskIdAndSectionIdAndItemId(String quoteNo, Integer valueOf, String sectionId,
			Integer valueOf2);


	List<ContentAndRisk> findByQuoteNoAndSectionId(String quoteNo, String sectionId);



	ContentAndRisk findByRequestReferenceNoAndRiskIdAndSectionIdAndQuoteNo(String requestReferenceNo, Integer valueOf,
			String sectionId, String quoteNo);


	List<ContentAndRisk> findByQuoteNo(String quoteNo);

	List<ContentAndRisk> findByQuoteNoAndType(String quoteNo, String type);


	Long countByQuoteNoAndRiskId(String quoteNo, Integer valueOf);

	
	@Transactional
	void deleteByQuoteNoAndRiskId(String quoteNo, Integer valueOf);


	

}
