/*
 * Java domain class for entity "CoverMaster" 
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-30 ( 18:45:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;

import com.maan.eway.bean.CoverMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.CoverMasterId;
import com.maan.eway.bean.CoverOfsGridMaster;
import com.maan.eway.bean.CoverOfsGridMasterId;
/**
 * <h2>CoverMasterRepository</h2>
 *
 * createdAt : 2022-09-30 - Time 18:45:30
 * <p>
 * Description: "CoverMaster" Repository
 */
 
 
 
public interface CoverOfsGridMasterRepository  extends JpaRepository<CoverOfsGridMaster,CoverOfsGridMasterId > , JpaSpecificationExecutor<CoverOfsGridMaster> {

	List<CoverOfsGridMaster> findByCoverIdAndSubCoverIdOrderByCoveragesSubIdAsc(Integer coverId, Integer subCoverId);

}
