/*
 * Java domain class for entity "DropdownTableDetails" 
 * Created on 2022-11-16 ( Date ISO 2022-11-16 - Time 16:18:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-16 ( 16:18:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.DropdownTableDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.DropdownTableDetailsId;
/**
 * <h2>DropdownTableDetailsRepository</h2>
 *
 * createdAt : 2022-11-16 - Time 16:18:45
 * <p>
 * Description: "DropdownTableDetails" Repository
 */
 
 
 
public interface DropdownTableDetailsRepository  extends JpaRepository<DropdownTableDetails,DropdownTableDetailsId > , JpaSpecificationExecutor<DropdownTableDetails> {

}
