/*
 * Java domain class for entity "DropdownTableDetailsArch" 
 * Created on 2022-11-16 ( Date ISO 2022-11-16 - Time 16:18:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-16 ( 16:18:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.DropdownTableDetailsArch;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.DropdownTableDetailsArchId;
/**
 * <h2>DropdownTableDetailsArchRepository</h2>
 *
 * createdAt : 2022-11-16 - Time 16:18:45
 * <p>
 * Description: "DropdownTableDetailsArch" Repository
 */
 
 
 
public interface DropdownTableDetailsArchRepository  extends JpaRepository<DropdownTableDetailsArch,DropdownTableDetailsArchId > , JpaSpecificationExecutor<DropdownTableDetailsArch> {

}
