/*
 * Java domain class for entity "EserviceCustomerDetails" 
 * Created on 2022-09-23 ( Date ISO 2022-09-23 - Time 15:08:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-23 ( 15:08:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.EserviceCustomerDetails;
import com.maan.eway.bean.EserviceCustomerDetailsId;
/**
 * <h2>EserviceCustomerDetailsRepository</h2>
 *
 * createdAt : 2022-09-23 - Time 15:08:00
 * <p>
 * Description: "EserviceCustomerDetails" Repository
 */
 
 
 
public interface EserviceCustomerDetailsRepository  extends JpaRepository<EserviceCustomerDetails,EserviceCustomerDetailsId > , JpaSpecificationExecutor<EserviceCustomerDetails> {

	EserviceCustomerDetails findByCustomerReferenceNo(String requestReferenceNo);

	List<EserviceCustomerDetails> findByCustomerReferenceNoInOrderByUpdatedDateDesc(List<String> custRefNos);

}
