/*
 * Java domain class for entity "EserviceCustomerDetails" 
 * Created on 2022-09-23 ( Date ISO 2022-09-23 - Time 15:08:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-23 ( 15:08:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.EserviceCustomerDetailsArch;
import com.maan.eway.bean.EserviceCustomerDetailsArchId;
/**
 * <h2>EserviceCustomerDetailsRepository</h2>
 *
 * createdAt : 2022-09-23 - Time 15:08:00
 * <p>
 * Description: "EserviceCustomerDetails" Repository
 */
 
 
 
public interface EserviceCustomerDetailsArchRepository  extends JpaRepository<EserviceCustomerDetailsArch,EserviceCustomerDetailsArchId > , JpaSpecificationExecutor<EserviceCustomerDetailsArch> {


}
