/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.EserviceCommonDetails;
import com.maan.eway.bean.EserviceCommonDetailsId;
/**
 * <h2>BankMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:26
 * <p>
 * Description: "BankMaster" Repository
 */
 
 
 
public interface EserviceCommonDetailsRepository  extends JpaRepository<EserviceCommonDetails,EserviceCommonDetailsId > , JpaSpecificationExecutor<EserviceCommonDetails> {

	List<EserviceCommonDetails> findByRequestReferenceNo(String requestReferenceNo);

	Long countByRequestReferenceNo(String refNo);

	@Transactional
	void deleteByRequestReferenceNo(String refNo);

	EserviceCommonDetails findByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer valueOf);

	List<EserviceCommonDetails> findByRequestReferenceNoOrderByRiskIdAsc(String requestReferenceNo);

	EserviceCommonDetails findByQuoteNo(String quoteNo);


}
