/*
 * Java domain class for entity "FactorTypeDetails" 
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-30 ( 18:45:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.FactorTypeDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.FactorTypeDetailsId;
/**
 * <h2>FactorTypeDetailsRepository</h2>
 *
 * createdAt : 2022-09-30 - Time 18:45:34
 * <p>
 * Description: "FactorTypeDetails" Repository
 */
 
 
 
public interface FactorTypeDetailsRepository  extends JpaRepository<FactorTypeDetails,FactorTypeDetailsId > , JpaSpecificationExecutor<FactorTypeDetails> {

}
