/*
 * Java domain class for entity "LoginMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.LoginMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.LoginMasterId;
/**
 * <h2>LoginMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:27
 * <p>
 * Description: "LoginMaster" Repository
 */
 
 
 
public interface LoginMasterRepository  extends JpaRepository<LoginMaster,LoginMasterId > , JpaSpecificationExecutor<LoginMaster> {

	LoginMaster findByLoginId(String loginId);

	LoginMaster findByLoginIdAndPassword(String userId, String epass);

	LoginMaster findByCompanyIdAndLoginId(String companyId, String loginId);

}
