/*
 * Java domain class for entity "LoginReferalMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.LoginReferalMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.LoginReferalMasterId;
/**
 * <h2>LoginReferalMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:27
 * <p>
 * Description: "LoginReferalMaster" Repository
 */
 
 
 
public interface LoginReferalMasterRepository  extends JpaRepository<LoginReferalMaster,LoginReferalMasterId > , JpaSpecificationExecutor<LoginReferalMaster> {

}
