/*
 * Java domain class for entity "MsAssetDetails" 
 * Created on 2022-11-18 ( Date ISO 2022-11-18 - Time 11:39:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-18 ( 11:39:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.MsAssetDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.MsAssetDetailsId;
/**
 * <h2>MsAssetDetailsRepository</h2>
 *
 * createdAt : 2022-11-18 - Time 11:39:00
 * <p>
 * Description: "MsAssetDetails" Repository
 */
 
 
 
public interface MsAssetDetailsRepository  extends JpaRepository<MsAssetDetails,MsAssetDetailsId > , JpaSpecificationExecutor<MsAssetDetails> {

}
