/*
 * Java domain class for entity "SeqPolicyno" 
 * Created on 2023-01-12 ( Date ISO 2023-01-12 - Time 16:02:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-12 ( 16:02:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;


import com.maan.eway.bean.SeqTrackingId;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
/**
 * <h2>SeqPolicynoRepository</h2>
 *
 * createdAt : 2023-01-12 - Time 16:02:00
 * <p>
 * Description: "SeqPolicyno" Repository
 */
 
 
 
public interface SeqTrackingRepository  extends JpaRepository<SeqTrackingId,Long > , JpaSpecificationExecutor<SeqTrackingId> {

}
