/*
 * Java domain class for entity "TravelPassDetails" 
 * Created on 2022-11-30 ( Date ISO 2022-11-30 - Time 17:07:05 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-30 ( 17:07:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.TravelPassengerDetails;
import com.maan.eway.bean.TravelPassengerDetailsId;
/**
 * <h2>TravelPassDetailsRepository</h2>
 *
 * createdAt : 2022-11-30 - Time 17:07:05
 * <p>
 * Description: "TravelPassDetails" Repository
 */
 
 

@Transactional
public interface TravelPassengerDetailsRepository  extends JpaRepository<TravelPassengerDetails,TravelPassengerDetailsId > , JpaSpecificationExecutor<TravelPassengerDetails> {


	Long countByQuoteNo(String quoteNo);

	void deleteByQuoteNo(String quoteNo);
	
	List<TravelPassengerDetails> findByQuoteNoOrderByPassengerIdAsc(String quoteNo);

	TravelPassengerDetails findByQuoteNoAndPassengerId(String quoteNo, Integer valueOf);

	List<TravelPassengerDetails> findByQuoteNoAndTravelIdOrderByPassengerIdAsc(String quoteNo, Integer integer);

}
