/*
 * Java domain class for entity "UwQuestionsDetails" 
 * Created on 2022-11-16 ( Date ISO 2022-11-16 - Time 16:19:16 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-16 ( 16:19:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.UwQuestionsDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.UwQuestionsDetailsId;
/**
 * <h2>UwQuestionsDetailsRepository</h2>
 *
 * createdAt : 2022-11-16 - Time 16:19:16
 * <p>
 * Description: "UwQuestionsDetails" Repository
 */
 
 
 
public interface UwQuestionsDetailsRepository  extends JpaRepository<UwQuestionsDetails,UwQuestionsDetailsId > , JpaSpecificationExecutor<UwQuestionsDetails> {

}
