/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-11-18 ( Date ISO 2022-11-18 - Time 11:38:42 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.common.service;
import java.util.List;

import com.maan.eway.bean.EserviceBuildingDetails;
import com.maan.eway.common.req.EservicePaccSaveReq;
import com.maan.eway.common.req.EservicePersonalAccGetById;
import com.maan.eway.common.res.EservicePaccGetRes;
import com.maan.eway.common.res.EservicePaccSaveRes;
import com.maan.eway.error.Error;
/**
* <h2>EserviceBuildingDetailsServiceimpl</h2>
*/
public interface EservicePersonalAccidentService  {

//boolean delete(long id);
List<Error> validatePersonalAccidentDetails(EservicePaccSaveReq req);
EservicePaccSaveRes savePersonalAccidentDetails(EservicePaccSaveReq req);
EservicePaccGetRes getPersonalAccidentDetailsByRiskId(EservicePersonalAccGetById req);
List<EservicePaccGetRes> getPersonalAccList(EservicePersonalAccGetById req);

}
