/*
 * Java domain class for entity "EserviceMotorDetails" 
 * Created on 2022-10-17 ( Date ISO 2022-10-17 - Time 11:50:07 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.common.res;

import java.io.Serializable;

import lombok.*;


import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonProperty;

 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class UwQuestionsRes implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("CustomerReferenceno")
    private String   customerReferenceNo ;
    
    @JsonProperty("RequestReferenceno")
    private String   requestReferenceNo ;
	
    @JsonProperty("DrivenByUnderAge")
    private String    drivenByUnderAge   ;
	@JsonProperty("DefectiveVisionOrHearing")
    private String    defectiveVisionOrHearing;
	@JsonProperty("MotoringOffence")
    private String    motoringOffence  ;
	@JsonProperty("SuspensionOfLicense")
    private String    suspensionOfLicense;
	@JsonProperty("SpecialTermsOfPremium")
    private String    specialTermsOfPremium;
	@JsonProperty("IrrespectiveOfBlame")
    private String    irrespectiveOfBlame;

}
