/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-19 ( Date ISO 2022-11-19 - Time 13:30:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-19 ( 13:30:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.eway.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import java.util.Date;
import javax.persistence.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BurglaryPolicyInfoId.class)
@Table(name = "burglary_policy_info")

public class BurglaryPolicyInfo implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "ID", nullable = false)
	private Integer id;

	@Id
	@Column(name = "COMPANY_ID", nullable = false, length = 10)
	private String companyId;

	@Id
	@Column(name = "BRANCH_CODE", nullable = false, length = 10)
	private String branchCode;

	@Id
	@Column(name = "PRODUCT_ID", nullable = false, length = 10)
	private String productId;

	@Id
	@Column(name = "SECTION_ID", nullable = false, length = 10)
	private String sectionId;

	@Id
	@Column(name = "RISK_ID", nullable = false)
	private Integer riskId;

	@Id
	@Column(name = "REQUEST_REFERENCE_NO", nullable = false, length = 20)
	private String requestReferenceNo;

	@Id
	@Column(name = "QUOTE_NO", nullable = false, length = 20)
	private String quoteNo;

	@Column(name = "LEFT_UNINHABITED", length = 2)
	private String leftUninhabited;

	@Column(name = "UNINHABITED_PER_YEAR")
	private Integer uninhabitedPerYear;

	@Column(name = "UNINHABITED_DAYS")
	private Integer uninhabitedDays;

	@Column(name = "PREMISES_OCCUPIED", length = 2)
	private String premisesOccupied;

	@Column(name = "EXTENT_OF_LOSS", length = 100)
	private String extentOfLoss;

	@Column(name = "PRECAUTION_TAKEN", length = 100)
	private String precautionTaken;

	@Column(name = "STOCK_BOOK_MAINTAINED", length = 2)
	private String stockBookMaintained;

	@Column(name = "STOCK_BOOK_LOSS", length = 2)
	private String stockBookLoss;

	@Column(name = "LAST_STOCK_TAKEN", length = 10)
	private String lastStockTaken;

	@Column(name = "SAFETY_LOCKER_NAME", length = 100)
	private String safetyLockerName;

	@Column(name = "BURGLAR_RESISTING_SAFE", length = 2)
	private String burglarResistingSafe;

	@Column(name = "SAFETY_LOCKER_HEIGHT")
	private BigDecimal safetyLockerHeight;

	@Column(name = "SAFETY_LOCKER_WIDTH")
	private BigDecimal safetyLockerWidth;

	@Column(name = "SAFETY_LOCKER_DEPTH")
	private BigDecimal safetyLockerDepth;

	@Column(name = "SAFETY_LOCKER_STRUCTURE", length = 100)
	private String safetyLockerStructure;

	@Column(name = "NUMBER_OF_KEYS")
	private Integer numberOfKeys;

	@Column(name = "OPEN_OPTION_ID")
	private Integer openOptionId;

	@Column(name = "OPEN_OPTION_DESC", length = 20)
	private String openOptionDesc;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;

	@Column(name = "CREATED_BY", length = 100)
	private String createdBy;

	@Column(name = "STATUS", length = 10)
	private String status;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE")
	private Date updatedDate;

	@Column(name = "UPDATED_BY", length = 100)
	private String updatedBy;

}
