/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-30 ( 18:45:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "CoverMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CoverOfsGridMasterId.class)
@Table(name="cover_ofs_grid_master")


public class CoverOfsGridMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COVER_ID", nullable=false)
    private Integer    coverId ;

    @Id
    @Column(name="SUB_COVER_ID", nullable=false)
    private Integer    subCoverId ;

    @Id
    @Column(name="COVERAGES_SUB_ID", nullable=false)
    private Integer    coveragesSubId ;
  
    //--- ENTITY DATA FIELDS 
    @Column(name="CALC_TYPE", length=1)
    private String     calcType ;

    @Column(name="CALC_TYPE_DESC", length=300)
    private String     calcTypeDesc ;

    @Column(name="START_SUMINSURED")
    private Double startSumInsured ;

    @Column(name="END_SUMINSURED")
    private Double endSumInsured ;

    @Column(name="BASE_RATE")
    private Double baseRate ;
    
    @Column(name="MINIMUM_PREMIUM")
    private Double minimumPremium ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;



}



