/*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.util.Date;

/**
 * Composite primary key for entity "DocumentMaster" ( stored in table "document_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class CoverDocumentMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    documentId ;
    
    private String     companyId ;
    
    private Integer    productId ;
    
    private Integer   sectionId ;
    
    private String coverId ;
    
    private Date       effectiveDateStart ;
    
    private Date       effectiveDateEnd ;
    
  

     
}
