/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "BankMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CustomerRelationshipId.class)
@Table(name="customer_relationship")


public class CustomerRelationship implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CUSTOMER_ID", nullable=false)
    private Integer   customerId;

    @Id 
    @Column(name="GST_NO", length=100, nullable=false)
    private String    gstNo;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId;
    
    @Id
    @Column(name="BROKER_ID", nullable=false)
    private Integer   brokerId;

    @Column(name="BRANCH_CODE", nullable=false, length=20)
    private String     branchCode;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;
    
    
    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date      updatedDate ;
    
    
}



