/*
 * Created on 2022-11-16 ( 16:18:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.util.Date;

/**
 * Composite primary key for entity "DropdownTableDetails" ( stored in table "dropdown_table_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class DropdownTableDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    requestId ;
    
    private Integer    itemId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private Integer    productId ;
    
    private Date       effectiveDateStart ;
    
    private Date       effectiveDateEnd ;
    
     
}
