/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-03-01 ( Date ISO 2023-03-01 - Time 11:29:43 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-03-01 ( 11:29:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "EndtTypeMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EndtTypeMasterId.class)
@Table(name="endt_type_master")


public class EndtTypeMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ENDT_TYPE_ID", nullable=false)
    private Integer    endtTypeId ;

    @Id
    @Column(name="ENDT_TYPE_CATEGORY_ID", nullable=false)
    private Integer    endtTypeCategoryId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=100)
    private String     companyId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="ENDT_TYPE", length=300)
    private String     endtType ;

    @Column(name="ENDT_TYPE_DESC", length=300)
    private String     endtTypeDesc ;

    @Column(name="ENDT_TYPE_CATEGORY", length=150)
    private String     endtTypeCategory ;

    @Column(name="STATUS", nullable=false, length=3)
    private String     status ;
    
    @Column(name="PRIORITY")
    private Integer    priority ;

    @Column(name="ENDT_DEPENDANT_IDS", length=100)
    private String     endtDependantIds ;

    @Column(name="ENDT_DEPENDANT_FIELDS", length=1000)
    private String     endtDependantFields ;

    @Column(name="CORE_APP_CODE", length=10)
    private String coreAppCode ;

    @Column(name="REGULATORY_CODE", length=10)
    private String regulatoryCode ;

    
    @Column(name="ENDT_FEE_YN")
    private String endtFeeYn ;
    
    @Column(name="ENDT_FEE_PERCENT")
    private String endtFeePercent ;

    @Column(name="REMARKS", length=100)
    private String remarks;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date entryDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date effectiveDateStart;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date effectiveDateEnd;

    @Column(name="CREATED_BY", length=100)
    private String createdBy;

    @Column(name="UPDATED_BY", length=100)
    private String updatedBy;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date updatedDate;

    @Column(name="AMEND_ID")
    private Integer amendId;

    @Column(name="CALC_TYPE_ID", length=10)
    private String calcTypeId;

    
}



