/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-19 ( Date ISO 2022-11-19 - Time 13:30:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-19 ( 13:30:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "EserviceMotorDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EserviceDriverDetailsId.class)
@Table(name="eservice_driver_details")


public class EserviceDriverDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;

    @Id
    @Column(name="DRIVER_ID", nullable=false, length=10)
    private Integer     driverId ;
    
    @Id
    @Column(name="LICENCE_NO", nullable=false, length=10)
    private String     licenceNo ;
    
    @Column(name="SECTION_ID", nullable=false, length=20)
    private Integer     sectionId ;
    
    @Column(name="PRODUCT_ID", nullable=false, length=20)
    private Integer     productId ;

    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;
    
    @Column(name="DRIVER_NAME", nullable=false, length=20)
    private String     driverName ;
    
    @Column(name="DRIVER_TYPE", nullable=false, length=20)
    private String     driverType ;
    
    @Column(name="DRIVER_TYPEDESC", nullable=false, length=20)
    private String     driverTypedesc ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRIVER_DOB")
    private Date     driverDob;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date     entryDate ;
    
    @Column(name="STATUS")
    private String     status ;
    
    @Column(name="CREATED_BY")
    private String     createdBy ;
    
}



