/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.eway.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * Domain class for entity "BankMaster"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ExchangeMasterId.class)
@Table(name = "eway_exchange_master")

public class ExchangeMaster implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "S_NO", nullable = false)
	private Integer sNo;

	@Id
	@Column(name = "EXCHANGE_ID", nullable = false)
	private Integer exchangeId;

	@Id
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_DATE_START", nullable = false)
	private Date effectiveDateStart;

	@Id
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFECTIVE_DATE_END", nullable = false)
	private Date effectiveDateEnd;

	// --- ENTITY DATA FIELDS
	@Column(name = "EXCHANGE_RATE")
	private Double exchangeRate;

	@Column(name = "COMPANY_ID", length = 20)
	private String companyId;

	@Column(name = "CURRENCY_ID", length = 20)
	private String currencyId;

	 @Column(name="CURRENCY_NAME", length=100)
    private String     currencyName;

	@Column(name = "AMEND_ID")
	private Integer amendId;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;

	@Column(name = "STATUS", length = 1)
	private String status;

	@Column(name = "REMARKS", length = 100)
	private String remarks;

}
