/*
 * Created on 2022-11-21 ( 15:19:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class FollowUpDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    private String followupId;
    private String requestReferenceNo;
    private String companyId;
    private String loginId;
    private String branchCode;
    private String productId;


}
