/*
 * Created on 2022-11-21 ( 15:19:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "BankMaster" ( stored in table "bank_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class IndustryMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    private String    categoryId ;

    private String     companyId ;
    
    private String     branchCode ;
    
    private String    productId ;

    private Integer  industryId ;

}
