/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "AcExecutiveMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(IndustryMasterId.class)
@Table(name="industry_master")


public class IndustryMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
@Id
@Column(name="INDUSTRY_ID", nullable=false)
private Integer  industryId ;


    @Id
    @Column(name="CATEGORY_ID", nullable=false, length=20)
    private String    categoryId ;

    
    @Id
    @Column(name="COMPANY_ID", nullable=false, length=100)
    private String    companyId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=100)
    private String    branchCode ;
    
    @Id
    @Column(name="PRODUCT_ID", nullable=false, length=100)
    private String    productId ;

    
    
    @Column(name="CATEGORY_DESC", length=100)
    private String categoryDesc ;

    @Column(name="INDUSTRY_NAME", length=100)
    private String industryName;
    

    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;

    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=10)
    private String     status ;
    
    @Column(name="REMARKS", length=100)
    private String     remarks;
    
    @Column(name="CREATED_BY", length=100)
    private String    createdBy;
    

    
    @Column(name="AMEND_ID")
    private Integer    amendId ;

    @Column(name="CORE_APP_CODE", length=20)
    private String    coreAppCode;
    
    @Column(name="REGULATORY_CODE", length=20)
    private String    regulatoryCode;
    
    @Column(name="UPDATED_BY", length=100)
    private String    updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

}



