/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-01-12 ( Date ISO 2023-01-12 - Time 16:01:20 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-01-12 ( 16:01:20 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "LoginUserInfo"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(LoginUserInfoId.class)
@Table(name="login_user_info")


public class LoginUserInfo implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOGIN_ID", nullable=false, length=50)
    private String     loginId ;

    @Id
    @Column(name="OA_CODE", nullable=false)
    private String    oaCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="AGENCY_CODE", length=20)
    private String     agencyCode ;

    @Column(name="USER_NAME", length=100)
    private String     userName ;

    @Column(name="USER_MOBILE", length=20)
    private String     userMobile ;

    @Column(name="USER_MAIL", length=50)
    private String     userMail ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="CREATED_BY", length=50)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=50)
    private String     updatedBy ;

    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="ADDRESS1", length=100)
    private String     address1 ;

    @Column(name="ADDRESS2", length=100)
    private String     address2 ;

    @Column(name="ADDRESS3", length=100)
    private String     address3 ;

    @Column(name="CITY_CODE")
    private Integer    cityCode ;

    @Column(name="STATE_CODE")
    private Integer    stateCode ;

    @Column(name="COUNTRY_CODE")
    private String    countryCode ;

    @Column(name="CITY_NAME", length=50)
    private String     cityName ;

    @Column(name="POBOX")
    private BigDecimal pobox ;

    @Column(name="STATE_NAME", length=50)
    private String     stateName ;

    @Column(name="FAX", length=50)
    private String     fax ;

    @Column(name="COUNTRY_NAME", length=50)
    private String     countryName ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="CUSTOMER_ID")
    private BigDecimal customerId ;

    @Column(name="BRANCH_CODE", length=100)
    private String     branchCode ;

    @Column(name="MISSIPPI_ID")
    private BigDecimal missippiId ;

    @Column(name="APPROVED_PREPARED_BY", length=30)
    private String     approvedPreparedBy ;

    @Column(name="AC_EXECUTIVE_ID")
    private BigDecimal acExecutiveId ;

    @Column(name="CORE_APP_BROKER_CODE", length=25)
    private String     coreAppBrokerCode ;

    @Column(name="VAT_REG_NO", length=100)
    private String     vatRegNo ;

    @Column(name="CHECKER_YN", length=10)
    private String     checkerYn ;

    @Column(name="MAKER_YN", length=10)
    private String     makerYn ;

    @Column(name="COMMISSION_VAT_YN", length=10)
    private String     commissionVatYn ;

    @Column(name="CUST_CONFIRM_YN", length=10)
    private String     custConfirmYn ;

    @Column(name="CONTACT_PERSON_NAME", length=100)
    private String     contactPersonName ;

    @Column(name="DESIGNATION", length=100)
    private String     designation ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;

    @Column(name="MOBILE_CODE", length=20)
    private String     mobileCode ;

    @Column(name="MOBILE_CODE_DESC", length=20)
    private String     mobileCodeDesc ;

    @Column(name="WHATSAPP_CODE", length=20)
    private String     whatsappCode ;

    @Column(name="WHATSAPP_CODE_DESC", length=20)
    private String     whatsappCodeDesc ;

    @Column(name="WHATSAPP_NO", length=20)
    private String     whatsappNo ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



