/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "login_broker_branch_master"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="login_branch_master_arch")


public class LoginBranchMasterArch implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
	@Id
	@Column(name="ARCH_ID", length=20)
	private String   archId ;

    @Column(name="LOGIN_ID", nullable=false, length=50)
    private String     loginId ;

   
    @Column(name="BRANCH_CODE", nullable=false, length=20)
    private String     branchCode ;

    
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    //--- ENTITY DATA FIELDS 
   
    
    @Column(name="AGENCY_CODE")
    private Integer     agencyCode ;

    @Column(name="ATTACHED_COMPANY", length=300)
    private String     attachedCompany ;
    
    
    @Column(name="ATTACHED_BRANCH", length=300)
    private String     attachedBranch ;

    @Column(name="OA_CODE", length=10)
    private String     oaCode ;

    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Column(name="UPDATED_BY", length=20)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="BROKER_BRANCH_CODE", length=20)
    private String     brokerBranchCode ;
    
    @Column(name="BROKER_BRANCH_NAME", length=100)
    private String     brokerBranchName;

}



