/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-03-03 ( Date ISO 2023-03-03 - Time 18:58:37 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-03-03 ( 18:58:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorRiskDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="motor_risk_detail")


public class MotorRiskDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUESTREFERENCENO", nullable=false, length=15)
    private String     requestreferenceno ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SERVICE_ID", length=40)
    private String     serviceId ;

    @Column(name="QUOTATION_POLICY_NO", length=100)
    private String     quotationPolicyNo ;

    @Column(name="SEC_CODE",length=100)
    private String     secCode ;

    @Column(name="SERVICE_ACTION", length=10)
    private String     serviceAction ;

    @Column(name="L1S1_ID", length=15)
    private String     l1s1Id ;

    @Column(name="ITERATION_NO")
    private Double     iterationNo ;

    @Column(name="VEHICLE_MAKE_MODEL", length=15)
    private String     vehicleMakeModel ;

    @Column(name="NAME", length=2000)
    private String     name ;

    @Column(name="COMMERCIAL_DISCOUNT", length=20)
    private String     commercialDiscount ;

    @Column(name="VEHICLE_TYPE", length=20)
    private String     vehicleType ;

    @Column(name="CREATED_BY", length=20)
    private String     createdBy ;

    @Column(name="CHASSIS_NO", length=20)
    private String     chassisNo ;

    @Column(name="ENGINE_NO", length=20)
    private String     engineNo ;

    @Column(name="IDRESIDENT_NO", length=20)
    private String     idresidentNo ;

    @Column(name="TYPE_OF_CLASS", length=20)
    private String     typeOfClass ;

    @Column(name="COUNTRY_OF_MAKE", length=20)
    private String     countryOfMake ;

    @Column(name="SUM_INSURED", length=20)
    private String     sumInsured ;

    @Column(name="IMPORT_VEHICLEYN", length=20)
    private String     importVehicleyn ;

    @Column(name="RISK_ID", length=20)
    private String     riskId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_OF_1ST_REGISTRATION")
    private Date       dateOf1stRegistration ;

    @Column(name="PLATE_NO", length=20)
    private String     plateNo ;

    @Column(name="CHARACTER", length=20)
    private String     character ;

    @Column(name="REGISTRATION_FORM_NO", length=20)
    private String     registrationFormNo ;

    @Column(name="GEOGRAPHICAL_EXTENSION", length=20)
    private String     geographicalExtension ;

    @Column(name="PROFESSION", length=20)
    private String     profession ;

    @Column(name="ORANGE_CARD_BOOK_ID", length=20)
    private String     orangeCardBookId ;

    @Column(name="ORANGE_CARD_NO", length=20)
    private String     orangeCardNo ;

    @Column(name="NCD", length=20)
    private String     ncd ;

    @Column(name="VEHICLE_CATEGORY", length=20)
    private String     vehicleCategory ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSURED_DRIVERS_DOB")
    private Date       insuredDriversDob ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DRIVING_LICENCE_ISSUED_ON")
    private Date       drivingLicenceIssuedOn ;


    @Column(name="ORANGE_CARD_YN", length=20)
    private String     orangeCardYn ;

    @Column(name="ORANGE_CARD_TYPE", length=20)
    private String     orangeCardType ;

    @Column(name="COUPON_CODE_TRAVEL", length=20)
    private String     couponCodeTravel ;

    @Column(name="COUPON_CODE_PA", length=20)
    private String     couponCodePa ;

    @Column(name="COUPON_CODE_HM", length=20)
    private String     couponCodeHm ;

    @Column(name="IMPORT_ORIGIN", length=20)
    private String     importOrigin ;

    @Column(name="OFF_ROAD_COVER", length=20)
    private String     offRoadCover ;

    @Column(name="AGENCY_REPAIR", length=20)
    private String     agencyRepair ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VEHICLE_EXIT_DATE")
    private Date       vehicleExitDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MULKIYA_FROM_DATE")
    private Date       mulkiyaFromDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MULKIYA_TO_DATE")
    private Date       mulkiyaToDate ;

    @Column(name="CURRENCY", length=20)
    private String     currency ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VEHICLE_ENTRY_DATE")
    private Date       vehicleEntryDate ;

    @Column(name="VEHICLE_TONNAGE_CC")
    private Double     vehicleTonnageCc ;

    @Column(name="SEATS")
    private Double     seats ;

    @Column(name="PLUS")
    private Double     plus ;

    @Column(name="YEAR_OF_MANUFACTURE")
    private Double     yearOfManufacture ;

    @Column(name="AMOUNT_CLAIMED_BEFORE")
    private Double     amountClaimedBefore ;

    @Column(name="NO_OF_CLAIMS",length=100)
    private String     noOfClaims ;

    @Column(name="AAA_ROADSIDE_ASSISTANCE_NO", length=4000)
    private String     aaaRoadsideAssistanceNo ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=5)
    private String     status ;

    @Column(name="REMARKS", length=500)
    private String     remarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQUEST_TIME")
    private Date       requestTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RESPONSE_TIME")
    private Date       responseTime ;

    @Column(name="P_WS_RESPONSE_TYPE", length=100)
    private String     pWsResponseType ;

    @Column(name="P_WS_ERROR", length=500)
    private String     pWsError ;

    @Column(name="QUOTE_NO",length=100)
    private String  quoteNo ;

    @Column(name="PRODUCT_CODE", length=50)
    private String     productCode ;

    @Column(name="VEHICLE_MILEAGE", length=250)
    private String     vehicleMileage ;

    @Column(name="EXP_CURR_YEAR_MILEAGE", length=250)
    private String     expCurrYearMileage ;

    @Column(name="LOYALTY_DISCOUNT", length=250)
    private String     loyaltyDiscount ;

    @Column(name="NO_OF_CARS_OWNED", length=250)
    private String     noOfCarsOwned ;

    @Column(name="MODEL_MANUAL", length=250)
    private String     modelManual ;

    @Column(name="TONNAGE", length=250)
    private String     tonnage ;

    @Column(name="ROP_VEHICLE_TYPE", length=250)
    private String     ropVehicleType ;

    @Column(name="ORANGE_COLL_BRANCH", length=60)
    private String     orangeCollBranch ;

    @Column(name="DISCOUNT_VOUCHER_CODE", length=100)
    private String     discountVoucherCode ;

    @Column(name="RENTAL_NO_OF_DAYS", length=100)
    private String     rentalNoOfDays ;

    @Column(name="COUNTRY_OF_DRIV_LICENSE", length=50)
    private String     countryOfDrivLicense ;

    @Column(name="COUPON_3M_NUMBER", length=20)
    private String     coupon3mNumber ;

    @Column(name="MAINTANCE_YEAR", length=10)
    private String     maintanceYear ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



