/*
 * Created on 2022-11-18 ( 11:38:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "MsAssetDetails" ( stored in table "ms_asset_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsAssetDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Long       vdRefno ;
    
    private Integer    locationId ;
    
    private Integer    productId ;
    
    private Integer    sectionId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private String     requestReferenceNo ;
    
    private Integer    endtTypeId ;
    
    private String    endtCategoryId ;

     
}
