/*
 * Created on 2022-11-30 ( 17:06:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "MsHumanDetails" ( stored in table "ms_human_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsHumanDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestReferenceNo ;
    
    private Integer    humanId ;
    
    private Long       vdRefno ;
    
    private Integer    groupId ;
    
    private Integer    endtTypeId ;
    
    private String    endtCategoryId ;
     
}
