/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-10-27 ( Date ISO 2022-10-27 - Time 12:39:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-10-27 ( 12:39:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MsVehicleDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MsVehicleDetailsId.class)
@Table(name="ms_vehicle_details")


public class MsVehicleDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="VEHICLE_ID", nullable=false, length=10)
    private String     vehicleId ;

    @Id
    @Column(name="VD_REFNO", nullable=false)
    private Long       vdRefno ;

    @Id
    @Column(name="status", nullable=false, length=20)
    private String     status ;
    
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=10)
    private String     requestReferenceNo;
    
    @Id
    @Column(name="ENDT_TYPE_ID")
    private Integer    endtTypeId ;
    
    @Id
    @Column(name="ENDT_CATEGORY_ID")
    private String    endtCategoryId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="ACCIDENT_YN", nullable=false, length=20)
    private String     accidentYn ;

    @Column(name="Wind_Screen_Cover_Requeired", nullable=false, length=50)
    private String     windScreenCoverRequeired ;

    @Column(name="INSURANCE_TYPE", nullable=false, length=10)
    private String     insuranceType ;

    @Column(name="Insurance_Class", nullable=false, length=10)
    private String     insuranceClass ;

    @Column(name="Owner_Category", nullable=false, length=10)
    private String     ownerCategory ;

    @Column(name="chassis_number", nullable=false, length=20)
    private String     chassisNumber ;

    @Column(name="Vehicle_Make", nullable=false, length=10)
    private String     vehicleMake ;

    @Column(name="Vehcile_Model", nullable=false, length=10)
    private String     vehcileModel ;

    @Column(name="Vehicle_Body_Type", nullable=false, length=20)
    private String     vehicleBodyType ;

    @Column(name="Fuel_Type", nullable=false, length=10)
    private String     fuelType ;

    @Column(name="MANUFACTURE_YEAR", length=10)
    private Integer     manufactureYear ;

    @Column(name="Manufacture_age", nullable=false)
    private Integer    manufactureAge ;

    @Column(name="registration_age")
    private Integer    registrationAge ;

    @Temporal(TemporalType.DATE)
    @Column(name="Registration_Year")
    private Date       registrationYear ;

    @Column(name="Seating_Capacity", nullable=false, length=20)
    private String     seatingCapacity ;

    @Column(name="Period_of_Insurance", nullable=false, length=10)
    private String     periodOfInsurance ;

    @Column(name="Wind_screen_sum_insured")
    private BigDecimal     windScreenSumInsured ;

    @Column(name="acccessories_sum_insured")
    private BigDecimal     acccessoriesSumInsured ;

    @Column(name="Sum_Insured")
    private BigDecimal     sumInsured ;

    @Column(name="ncdyears", nullable=false)
    private Integer    ncdyears ;

    @Column(name="NCD_YN", nullable=false, length=5)
    private String     ncdYn ;

    @Column(name="No_OF_Claims", nullable=false)
    private Integer    noOfClaims ;

    @Temporal(TemporalType.DATE)
    @Column(name="entry_date", nullable=false)
    private Date       entryDate ;

    @Column(name="Vehicle_Weight", nullable=false)
    private BigDecimal       vehicleWeight ;

    @Column(name="CURRENCY", nullable=false)
    private String    currency ;

    @Column(name="EXCHANGE_RATE", nullable=false)
    private BigDecimal     exchangeRate ;

    @Column(name="FLEET_OWNER_YN", nullable=false, length=1)
    private String     fleetOwnerYn ;

    @Column(name="NO_OF_VEHICLES", nullable=false)
    private Integer    noOfVehicles ;

    @Column(name="NO_OF_COMPEHENSIVES", nullable=false)
    private Integer    noOfCompehensives ;

    @Column(name="CLAIM_RATIO", nullable=false)
    private BigDecimal     claimRatio ;

    

    @Column(name="TPD_INCREASE_LIMIT" )
    private BigDecimal     tpdIncreaseLimit ;

    @Column(name="MOTOR_USAGE")
    private String motorUsage;
    //--- ENTITY LINKS ( RELATIONSHIP )

    @Column(name="GPS_YN")
    private String gpsyn;
    

    @Column(name="GROUP_COUNT")
    private Integer groupCount;
    
    @Column(name="CITY_LIMIT", length=20)
    private String     cityLimit ;
    
    @Column(name="HAVEPROMOCODE", length=10)
    private String     havepromocode ;

    @Column(name="PROMOCODE", length=100)
    private String     promocode ;
    
   
    
}



