/*
 * Created on 2022-10-27 ( 12:39:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "MsVehicleDetails" ( stored in table "ms_vehicle_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsVehicleDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     vehicleId ;
    
    private Long       vdRefno ;
    
    private String     status ;    
  
    private String     chassisNumber ;
    
    private Integer    endtTypeId ;
    
    private String    endtCategoryId ;
}
