/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-30 ( 18:45:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "NotifTemplateMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(NotifTemplateMasterId.class)
@Table(name="eway_notif_template_master")


public class NotifTemplateMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SNO", nullable=false)
    private Integer    sno ;

    @Id
    @Column(name="INS_ID", nullable=false, length=100)
    private String     insId ;

   
    @Id
    @Column(name="EFFECTIVE_DATE_START", nullable=false)
    private Date       effectiveDateStart ;


    @Id
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE_END", nullable=false)
    private Date       effectiveDateEnd ;
    
    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;

    @Id
    @Column(name="QUERY_KEY", nullable=false, length=100)
    private String     queryKey ;

    //--- ENTITY DATA FIELDS 
    @Column(name="MAIL_REQUIRED", length=10)
    private String     mailRequired ;

    @Column(name="MAIL_SUBJECT", length=500)
    private String     mailSubject ;

    @Column(name="MAIL_BODY", length=2000)
    private String     mailBody ;

    @Column(name="MAIL_REGARDS", length=500)
    private String     mailRegards ;

    @Column(name="MODEL_NAME_EN", length=500)
    private String     modelNameEn ;

    @Column(name="MAIL_BODY_AR", length=500)
    private String     mailBodyAr ;

    @Column(name="MAIL_REGARDS_AR", length=500)
    private String     mailRegardsAr ;

    @Column(name="SMS_REQUIRED", length=10)
    private String     smsRequired ;

    @Column(name="SMS_SUBJECT", length=500)
    private String     smsSubject ;

    @Column(name="SMS_BODY_EN", length=2000)
    private String     smsBodyEn ;

    @Column(name="SMS_BODY_AR", length=500)
    private String     smsBodyAr ;

    @Column(name="SMS_REGARDS", length=500)
    private String     smsRegards ;

    @Column(name="SMS_REGARDS_AR", length=500)
    private String     smsRegardsAr ;

    @Column(name="WHATSAPP_REQUIRED", length=10)
    private String     whatsappRequired ;

    @Column(name="WHATSAPP_SUBJECT", length=500)
    private String     whatsappSubject ;

    @Column(name="WHATSAPP_BODY_EN", length=500)
    private String     whatsappBodyEn ;

    @Column(name="WHATSAPP_BODY_AR", length=500)
    private String     whatsappBodyAr ;

    @Column(name="WHATSAPP_REGARDS", length=500)
    private String     whatsappRegards ;

    @Column(name="WHATSAPP_REGARDS_AR", length=500)
    private String     whatsappRegardsAr ;

    @Column(name="NOTIFICATION_APPLICABLE", length=500)
    private String     notificationApplicable ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="STATUS", length=10)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @Column(name="CREATED_BY", length=10)
    private String     createdBy ;
    
    @Column(name="CORE_APP_CODE", length=20)
    private String     coreAppCode ;
    
    @Column(name="REGULATORY_CODE", length=20)
    private String     regulatoryCode ;

   


}



