/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.eway.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * Domain class for entity "BankMaster"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OccupationMasterId.class)
@Table(name = "eway_occupation_master")

public class OccupationMaster implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "OCCUPATION_ID", nullable = false, length = 20)
	private Integer occupationId;


    @Id
    @Column(name="AMEND_ID")
    private Integer     amendId ;
    
    @Id
    @Column(name="COMPANY_ID", length=20)
    private String     companyId;

    @Id
    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode;

    @Id
    @Column(name="PRODUCT_ID", length=20)
    private String    productId;

    
    @Column(name = "CATEGORY_ID", nullable = false, length = 20)
	private String categoryId;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START", nullable=false)
    private Date       effectiveDateStart ;

    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END", nullable=false)
    private Date       effectiveDateEnd ;


	// --- ENTITY DATA FIELDS
	@Column(name = "OCCUPATION_NAME", length = 100)
	private String occupationName;

	@Column(name = "OCCUPATION_NAME_AR", length = 100)
	private String occupationNameAr;

	@Column(name = "CORE_APPCODE", length = 20)
	private String coreAppcode;

	@Column(name = "REGULATORY_CODE", length = 20)
	private String regulatoryCode;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;

	@Column(name = "STATUS", length = 1)
	private String status;

	@Column(name = "REMARKS", length = 100)
	private String remarks;

	@Column(name = "CREATED_BY", length = 100)
	private String createdBy;

	@Column(name = "UPDATED_BY", length = 100)
	private String updatedBy;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE")
	private Date updatedDate;

}
