/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-08-24 ( 12:58:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import io.swagger.models.auth.In;
import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import java.util.Date;
import java.util.List;
import javax.persistence.*;




/**
* Domain class for entity "OfsGridMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(OfsGridMasterId.class)
@Table(name="ofs_grid_master")


public class OfsGridMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COVER_ID", nullable=false)
    private Integer    coverId ;
    
    @Id
    @Column(name="SCHEME_ID", nullable=false)
    private Integer    schemeId ;
    
    @Id
    @Column(name="CONTENT_TYPE_ID", nullable=false)
    private Integer    contentTypeId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Column(name="RATING_ID")
    private Integer   ratingId;
    
    @Id
    @Column(name="COVERAGES_ID", nullable=false)
    private Integer    coveragesId ;

    @Id
    @Column(name="COVERAGES_SUB_ID", nullable=false)
    private Integer    coveragesSubId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="START_SUMINSURED")
    private BigDecimal     startSuminsured ;

    @Column(name="END_SUMINSURED")
    private BigDecimal     END_SUMINSURED ;

    @Column(name="BASE_RATE")
    private BigDecimal     baseRate ;

    @Column(name="MINIMUM_PREMIUM")
    private BigDecimal     minimumPremium ;
    
    @Column(name="AMEND_ID")
    private Integer     amendId ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE")
    private Date       endDate ;

    @Column(name="CALC_TYPE", length=2)
    private String     calcType ;
    
    @Column(name="AGENCY_CODE", length=25)
    private String     AGENCY_CODE ;
    
    @Column(name="CORE_APP_CODE", length=20)
    private String     coreAppCode ;
}



