/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:20:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:20:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "PersonalInfo"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(PersonalInfoId.class)
@Table(name="personal_info")


public class PersonalInfo implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CUSTOMER_ID", nullable=false, length=20)
    private String     customerId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Column(name="CUSTOMER_REFERENCE_NO", nullable=false, length=20)
    private String     customerReferenceNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CLIENT_NAME", length=100)
    private String     clientName ;

    @Column(name="ADDRESS_1", length=100)
    private String     address1 ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="ADDRESS_2", length=100)
    private String     address2 ;

    @Column(name="TITLE", length=1)
    private String     title ;

    @Column(name="TITLE_DESC", length=20)
    private String     titleDesc ;

    @Column(name="CLIENT_STATUS", length=20)
    private String     clientStatus ;

    @Column(name="CLIENT_STATUS_DESC", length=100)
    private String     clientStatusDesc ;

    @Column(name="POLICY_HOLDER_TYPE", length=2)
    private String     policyHolderType ;

    @Column(name="POLICY_HOLDER_TYPEID", nullable=false, length=100)
    private String     policyHolderTypeid ;

    @Column(name="VR_TIN_NO", length=20)
    private String     vrTinNo ;

    @Column(name="ID_TYPE", nullable=false, length=100)
    private String     idType ;

    @Column(name="ID_TYPE_DESC", length=100)
    private String     idTypeDesc ;

    @Column(name="ID_NUMBER", nullable=false, length=100)
    private String     idNumber ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DOB_OR_REG_DATE")
    private Date       dobOrRegDate ;

    @Column(name="AGE", nullable=false)
    private Integer    age ;

    @Column(name="NATIONALITY", length=20)
    private String     nationality ;

    @Column(name="PLACE_OF_BIRTH", length=100)
    private String     placeOfBirth ;

    @Column(name="GENDER", nullable=false, length=1)
    private String     gender ;

    @Column(name="GENDER_DESC", length=20)
    private String     genderDesc ;

    @Column(name="OCCUPATION", nullable=false, length=10)
    private String     occupation ;

    @Column(name="OCCUPATION_DESC", length=20)
    private String     occupationDesc ;

    @Column(name="BUSINESS_TYPE",  length=1)
    private String     businessType ;

    @Column(name="BUSINESS_TYPE_DESC", length=20)
    private String     businessTypeDesc ;

    @Column(name="VRN_GST", length=20)
    private String     vrnGst ;

    @Column(name="REGION_CODE", nullable=false, length=20)
    private String     regionCode ;

    @Column(name="STATE_CODE", length=20)
    private String     stateCode ;

    @Column(name="STATE_NAME", length=100)
    private String     stateName ;

    @Column(name="CITY_CODE", length=20)
    private String     cityCode ;

    @Column(name="CITY_NAME", length=100)
    private String     cityName ;

    @Column(name="STREET", length=100)
    private String     street ;

    @Column(name="FAX", length=20)
    private String     fax ;

    @Column(name="TELEPHONE_NO_1", length=20)
    private String     telephoneNo1 ;

    @Column(name="TELEPHONE_NO_2", length=20)
    private String     telephoneNo2 ;

    @Column(name="TELEPHONE_NO_3", length=20)
    private String     telephoneNo3 ;

    @Column(name="MOBILE_NO_1", length=20)
    private String     mobileNo1 ;

    @Column(name="MOBILE_NO_2", length=20)
    private String     mobileNo2 ;

    @Column(name="MOBILE_NO_3", length=20)
    private String     mobileNo3 ;

    @Column(name="EMAIL_1", length=20)
    private String     email1 ;

    @Column(name="EMAIL_2", length=20)
    private String     email2 ;

    @Column(name="EMAIL_3", length=20)
    private String     email3 ;

    @Column(name="LANGUAGE", length=1)
    private String     language ;

    @Column(name="LANGUAGE_DESC", length=20)
    private String     languageDesc ;

    @Column(name="IS_TAX_EXEMPTED", nullable=false, length=1)
    private String     isTaxExempted ;

    @Column(name="TAX_EXEMPTED_ID", length=20)
    private String     taxExemptedId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Column(name="POLICY_HODER_TYPE_DESC", length=100)
    private String     policyHoderTypeDesc ;

    @Column(name="POLICY_HODER_TYPE_ID_DESC", length=100)
    private String     policyHoderTypeIdDesc ;

    @Column(name="POLICY_HOLDER_TYPE_DESC", length=100)
    private String     policyHolderTypeDesc ;

    @Column(name="POLICY_HOLDER_TYPE_ID_DESC", length=100)
    private String     policyHolderTypeIdDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPOINTMENT_DATE")
    private Date       appointmentDate ;

    @Column(name="PREFERRED_NOTIFICATION", length=20)
    private String     preferredNotification ;

    //--- ENTITY LINKS ( RELATIONSHIP )


}



