/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-12-05 ( Date ISO 2022-12-05 - Time 18:54:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-12-05 ( 18:54:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "PremiaCustomerDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(PremiaCustomerDetailsId.class)
@Table(name="premia_customer_details")


public class PremiaCustomerDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SERIAL_NO", nullable=false)
    private Double     serialNo ;

    @Id
    @Column(name="CUSTOMER_CODE", nullable=false, length=10)
    private String     customerCode ;
    
    @Id
    @Column(name="COMPANY_ID", nullable=false, length=10)
    private String     companyId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CUSTOMER_TYPE", length=10)
    private String     customerType ;

    @Column(name="CUSTOMER_TYPE_DESCRIPTION", length=100)
    private String     customerTypeDescription ;

    @Column(name="CUSTOMER_CATEGORY")
    private Double     customerCategory ;

    @Column(name="CUSTOMER_CATEGORY_DESC", length=100)
    private String     customerCategoryDesc ;

    @Column(name="CUSTOMER_NAME", length=300)
    private String     customerName ;

    @Column(name="GENDER", length=10)
    private String     gender ;

    @Column(name="CUST_CIVIL_ID", length=50)
    private String     custCivilId ;

    @Column(name="MARITAL_STATUS", length=20)
    private String     maritalStatus ;

    @Column(name="SOCIAL_SECURITY_NO", length=20)
    private String     socialSecurityNo ;

    @Column(name="AML_COMPLIANT_YN", length=10)
    private String     amlCompliantYn ;

    @Column(name="AML_VERIFIED_YN", length=10)
    private String     amlVerifiedYn ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="AML_VERIFIED_DATE")
    private Date       amlVerifiedDate ;

    @Column(name="IDENTITY_PROOF", length=100)
    private String     identityProof ;

    @Column(name="IDENTITY_NO", length=100)
    private String     identityNo ;

    @Column(name="PLACE_OF_BIRTH", length=100)
    private String     placeOfBirth ;

    @Column(name="NATIONALITY", length=100)
    private String     nationality ;

    @Column(name="OCCUPATION", length=500)
    private String     occupation ;

    @Column(name="POSITION_HELD", length=500)
    private String     positionHeld ;

    @Column(name="RES_ADDRESS_LINE_1", length=200)
    private String     resAddressLine1 ;

    @Column(name="RES_ADDRESS_LINE_2", length=200)
    private String     resAddressLine2 ;

    @Column(name="RES_ADDRESS_LINE_3", length=200)
    private String     resAddressLine3 ;

    @Column(name="RES_COUNTRY", length=100)
    private String     resCountry ;

    @Column(name="RES_STATE", length=100)
    private String     resState ;

    @Column(name="RES_CITY", length=100)
    private String     resCity ;

    @Column(name="RES_PHONE", length=100)
    private String     resPhone ;

    @Column(name="RES_FAX", length=50)
    private String     resFax ;

    @Column(name="EMPLOYERS_NAME", length=200)
    private String     employersName ;

    @Column(name="OFFICE_ADDRESS_LINE_1", length=200)
    private String     officeAddressLine1 ;

    @Column(name="OFFICE_ADDRESS_LINE_2", length=200)
    private String     officeAddressLine2 ;

    @Column(name="OFFICE_ADDRESS_LINE_3", length=200)
    private String     officeAddressLine3 ;

    @Column(name="OFFICE_COUNTRY", length=100)
    private String     officeCountry ;

    @Column(name="OFFICE_STATE", length=100)
    private String     officeState ;

    @Column(name="OFFICE_CITY", length=100)
    private String     officeCity ;

    @Column(name="OFFICE_PHONE", length=100)
    private String     officePhone ;

    @Column(name="OFFICE_EMAIL1", length=100)
    private String     officeEmail1 ;

    @Column(name="BRANCH_CODE", length=50)
    private String     branchCode;

    @Column(name="DIVISION_TO", length=50)
    private String     divisionTo ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_FROM")
    private Date       effectiveFrom ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_TO")
    private Date       effectiveTo ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=300)
    private String     remarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="DATE_OF_BIRTH")
    private Double     dateOfBirth ;

    @Column(name="CUSTOMER_ATTACHED_TO", length=50)
    private String     customerAttachedTo ;

    @Column(name="PREMIA_STATUS", length=50)
    private String     premiaStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_OF_BIRTH_1")
    private Date       dateOfBirth1 ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



