/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-02 ( 18:14:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "SectionMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ProductCoverRatingMasterId.class)
@Table(name="product_cover_rating_master")


public class ProductCoverRatingMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
	@Id
	@Column(name="RATING_ID", nullable=false)
	private Integer    ratingId ;
	
	@Id
	@Column(name="COVER_ID", nullable=false)
	private Integer    coverId ;
	
	@Id
	@Column(name="PRODUCT_ID", nullable=false)
	private Integer    productId ;
	
	@Id
	@Column(name="SECTION_ID", nullable=false)
	private Integer    sectionId ;
	
	@Id
	@Column(name="COMPANY_ID", nullable=false)
	private String    companyId ;
	
	@Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START", nullable=false)
    private Date       effectiveDateStart ;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END", nullable=false)
    private Date       effectiveDateEnd ;

    //--- ENTITY DATA FIELDS 
    @Column(name="RATING_SETUP_NAME", length=100)
    private String     ratingSetupName ;
    
    @Column(name="RATING_SETUP_SHORT", length=100)
    private String     ratingSetupShort ;
    
    @Column(name="COVERAGE_TYPE")
    private String     coverageType ;
    
    @Column(name="UPLOAD_OPTION")
    private String     uploadOption ;
    
    @Column(name="MAX_SUMINSURED")
    private Double maxSumInsured ;
    
    @Column(name="COVERAGE_LIMIT")
    private Double coverageLimit ;
    
    @Column(name="CALC_TYPE")
    private String     calcType ;
    
    @Column(name="BASE_RATE")
    private String     baseRate ;
    
    @Column(name="CALC_YN")
    private String calcYn ;
    
    @Column(name="EXCESS")
    private Double excess ;
    
    @Column(name="MIN_PREMIUM")
    private Double minPremium ;
    
    @Column(name="COVER_SHORT_DESC")
    private String     coverShortDesc ;
    
    @Column(name="COVER_NAME")
    private String coverName ;     
    
    @Column(name="CALC_STATUS")
    private String     calcStatus ;
    
    @Column(name="TOOL_TIP")
    private String     tooltip ; 
    
    @Column(name="CORE_CODE")
    private String     coreCode ;
    
    @Column(name="MIN_SUMINSURED")
    private Double minSumisured ;
    
    @Column(name="CORE_APP_CODE")
    private String coreAppCode ;
    
    @Column(name="AMEND_ID")
    private Integer amendId ;  

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date entryDate ;
    
    @Column(name="STATUS")
    private String status;
    
    @Column(name="CREATED_BY")
    private String createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date updatedDate ;
    
    @Column(name="UPDATED_BY")
    private String updatedBy ;
    
}



