/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-30 ( 18:45:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "CoverMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(SectionCoverOfsGridMasterId.class)
@Table(name="section_cover_ofs_grid_master")


public class SectionCoverOfsGridMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COVER_ID", nullable=false)
    private Integer    coverId ;

    @Id
    @Column(name="SUB_COVER_ID", nullable=false)
    private Integer    subCoverId ;
    
    @Id
    @Column(name="COVERAGES_SUB_ID", nullable=false)
    private Integer    coveragesSubId ;
    
    @Id
    @Column(name="SECTION_ID", nullable=false)
    private Integer    sectionId ;
    
    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;
    
    @Id
    @Column(name="COMPANY_ID", nullable=false)
    private String companyId ;
    

  
    //--- ENTITY DATA FIELDS 
    @Column(name="CALC_TYPE", length=1)
    private String     calcType ;

    @Column(name="CALC_TYPE_DESC", length=300)
    private String     calcTypeDesc ;

    @Column(name="MINIMUM_PREMIUM")
    private Double minimumPremium ;
    
    @Column(name="START_SUMINSURED")
    private Double startSumInsured ;

    @Column(name="END_SUMINSURED")
    private Double endSumInsured ;

    @Column(name="BASE_RATE")
    private Double baseRate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;



}



