/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.util.Date;

/**
 * Composite primary key for entity "AcExecutiveMaster" ( stored in table "ac_executive_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class SmsDataDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    private String sNo;
   // private String     companyId ;
   // private String   branchCode;

     
}
