/*
 * Created on 2022-11-21 ( 15:20:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;
 
import javax.persistence.Column;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
 

/**
 * Composite primary key for entity "UwQuestionsDetails" ( stored in table "uw_questions_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class UwQuestionsDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;
 
    //--- ENTITY KEY ATTRIBUTES 
    private String     companyId ;
    
    private Integer    productId ;
    
    private String     requestReferenceNo ;
    
    private Integer    vehicleId ;
    
    private Integer    uwQuestionId ;
    
 
     
}
