/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-03-03 ( Date ISO 2023-03-03 - Time 18:59:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-03-03 ( 18:59:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "YiChargeDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(YiChargeDetailId.class)
@Table(name="yi_charge_detail")


public class YiChargeDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CHARGE_CODE", nullable=false, length=100)
    private String     chargeCode ;

    @Id
    @Column(name="REQUESTREFERENCENO", nullable=false, length=15)
    private String     requestreferenceno ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SERVICE_ID", length=40)
    private String     serviceId ;

    @Column(name="QUOTATION_POLICY_NO", length=40)
    private String     quotationPolicyNo ;

    @Column(name="SERVICE_ACTION", length=60)
    private String     serviceAction ;

    @Column(name="CHG_ID")
    private BigDecimal chgId ;

    @Column(name="INDEX_NO", length=5)
    private String     indexNo ;

    @Column(name="CHARGE_RATE")
    private Double     chargeRate ;

    @Column(name="RATE_MODIFIED_YN", length=5)
    private String     rateModifiedYn ;

    @Column(name="CHARGE_AMOUNT")
    private Double     chargeAmount ;

    @Column(name="CHARGE_MODIFIED_YN", length=5)
    private String     chargeModifiedYn ;

    @Column(name="PROD_CODE", length=12)
    private String     prodCode ;

    @Column(name="P_WS_RESPONSE_TYPE", length=50)
    private String     pWsResponseType ;

    @Column(name="P_WS_ERROR", length=50)
    private String     pWsError ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQUEST_TIME")
    private Date       requestTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RESPONSE_TIME")
    private Date       responseTime ;

    @Column(name="STATUS", length=10)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



