/*
 * Java domain class for entity "MsVehicleDetails" 
 * Created on 2022-10-19 ( Date ISO 2022-10-19 - Time 17:10:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.res;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MsVehicleDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MsVehicleDetailsRes implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Vehicleid")
    private String     vehicleId    ;
	@JsonProperty("Vdrefno")
    private Long       vdRefno      ;
	@JsonProperty("Status")
    private String     status       ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Accidentyn")
    private String     accidentYn   ;
	@JsonProperty("Windscreencoverrequeired")
    private String     windScreenCoverRequeired ;
	@JsonProperty("Insurancetype")
    private String     insuranceType ;
	@JsonProperty("Insuranceclass")
    private String     insuranceClass ;
	@JsonProperty("Ownercategory")
    private String     ownerCategory ;
	@JsonProperty("Chassisnumber")
    private String     chassisNumber ;
	@JsonProperty("Vehiclemake")
    private String     vehicleMake  ;
	@JsonProperty("Vehcilemodel")
    private String     vehcileModel ;
	@JsonProperty("Vehiclebodytype")
    private String     vehicleBodyType ;
	@JsonProperty("Fueltype")
    private String     fuelType     ;
	@JsonProperty("Manufactureyear")
    private Date       manufactureYear ;
	@JsonProperty("Manufactureage")
    private Integer    manufactureAge ;
	@JsonProperty("Registrationage")
    private Integer    registrationAge ;
	@JsonProperty("Registrationyear")
    private Date       registrationYear ;
	@JsonProperty("Seatingcapacity")
    private String     seatingCapacity ;
	@JsonProperty("Periodofinsurance")
    private String     periodOfInsurance ;
	@JsonProperty("Windscreensuminsured")
    private Double     windScreenSumInsured ;
	@JsonProperty("Acccessoriessuminsured")
    private Double     acccessoriesSumInsured ;
	@JsonProperty("Suminsured")
    private Double     sumInsured   ;
	@JsonProperty("Ncdyears")
    private Integer    ncdyears     ;
	@JsonProperty("Ncdyn")
    private String     ncdYn        ;
	@JsonProperty("Noofclaims")
    private Integer    noOfClaims   ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
