/*
 * Java domain class for entity "EwayUploadTypeMaster" 
 * Created on 2023-05-11 ( Date ISO 2023-05-11 - Time 16:44:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-05-11 ( 16:44:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.batch.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.batch.entity.EwayUploadTypeMaster;
import com.maan.eway.batch.entity.EwayUploadTypeMasterId;
/**
 * <h2>EwayUploadTypeMasterRepository</h2>
 *
 * createdAt : 2023-05-11 - Time 16:44:27
 * <p>
 * Description: "EwayUploadTypeMaster" Repository
 */
 
 
 
public interface EwayUploadTypeMasterRepository  extends JpaRepository<EwayUploadTypeMaster,EwayUploadTypeMasterId > , JpaSpecificationExecutor<EwayUploadTypeMaster> {


	EwayUploadTypeMaster findByCompanyIdAndProductIdAndTypeidAndStatus(Integer companyId, Integer productId, Integer typeId, String status);

	
}
