/*
 * Java domain class for entity "EwayXlconfigMaster" 
 * Created on 2023-05-11 ( Date ISO 2023-05-11 - Time 16:44:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-05-11 ( 16:44:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.batch.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.batch.entity.EwayXlconfigMaster;
import com.maan.eway.batch.entity.EwayXlconfigMasterId;
/**
 * <h2>EwayXlconfigMasterRepository</h2>
 *
 * createdAt : 2023-05-11 - Time 16:44:28
 * <p>
 * Description: "EwayXlconfigMaster" Repository
 */
 
 
 
public interface EwayXlconfigMasterRepository  extends JpaRepository<EwayXlconfigMaster,EwayXlconfigMasterId > , JpaSpecificationExecutor<EwayXlconfigMaster> {


	List<EwayXlconfigMaster> findByCompanyIdAndProductIdAndTypeidAndStatusIgnoreCaseOrderByExcelColumnIndex(Integer companyId,
			Integer productId, Integer typeId, String status);

}
